### ISSUE TITLE
Add hamburger menu and implement basic/advanced farming sections

### ISSUE THREAD

**Issue by CryptoExplor** [CryptoExplor/farmlabs#1]
Add a hamburger menu and split functionality into basic/advanced sections with the following changes:

### Hamburger Menu Structure
```
- Basic
  - Basic Farming
  - Basic Farming Infographics
- Advanced
  - Advanced Farming
  - Advanced Farming Infographics
```

### Changes Required

1. Add Left Side Hamburger Menu:
   - Add a collapsible side menu with Basic and Advanced sections
   - Style menu to match existing design theme
   - Implement smooth transitions for menu open/close

2. Basic Farming Page Changes:
   - Create new basic farming page based on current template
   - Add chain connection information display:
     ```
     - Chain ID
     - Chain Name
     - Chain Gas Price
     - Native Coin
     ```
   - Remove Wallets section
   - Add connected wallet transaction tracking
   - Remove "Loaded Wallets to Interact with Each Other" from Recipient Settings
   - Keep Configuration section unchanged
   - Keep core transaction logic unchanged

3. Advanced Farming Page:
   - Keep current implementation as is
   - Rename to "Advanced Farming"

4. Infographics Pages:
   - Split current infographics into basic and advanced versions
   - Create new basic farming infographics
   - Rename current infographics to advanced farming infographics

### CSS Updates Needed
```css
/* Add new hamburger menu styles */
.hamburger-menu {
  position: fixed;
  left: 0;
  top: 0;
  height: 100%;
  background: #ffffff;
  width: 250px;
  transform: translateX(-100%);
  transition: transform 0.3s ease;
  z-index: 1000;
}

.hamburger-menu.open {
  transform: translateX(0);
}

/* Add menu toggle button styles */
.menu-toggle {
  position: fixed;
  left: 20px;
  top: 20px;
  z-index: 1001;
  background: none;
  border: none;
  cursor: pointer;
}

/* Update main content padding */
.main-content {
  padding-left: 60px;
  transition: padding-left 0.3s ease;
}

.main-content.menu-open {
  padding-left: 270px;
}
```

### JavaScript Updates Needed
```javascript
// Add menu toggle functionality
const menuToggle = document.querySelector('.menu-toggle');
const hamburgerMenu = document.querySelector('.hamburger-menu');
const mainContent = document.querySelector('.main-content');

menuToggle.addEventListener('click', () => {
  hamburgerMenu.classList.toggle('open');
  mainContent.classList.toggle('menu-open');
});

// Add page navigation handling
const menuLinks = document.querySelectorAll('.menu-link');
menuLinks.forEach(link => {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    const page = e.target.getAttribute('data-page');
    navigateToPage(page);
  });
});
```

### HTML Updates Needed
```html
<!-- Add hamburger menu structure -->
<button class="menu-toggle">☰</button>
<nav class="hamburger-menu">
  <div class="menu-section">
    <h3>Basic</h3>
    <a href="#" class="menu-link" data-page="basic-farming">Basic Farming</a>
    <a href="#" class="menu-link" data-page="basic-infographics">Basic Infographics</a>
  </div>
  <div class="menu-section">
    <h3>Advanced</h3>
    <a href="#" class="menu-link" data-page="advanced-farming">Advanced Farming</a>
    <a href="#" class="menu-link" data-page="advanced-infographics">Advanced Infographics</a>
  </div>
</nav>

<!-- Add chain info display to basic farming -->
<div class="chain-info-display">
  <div class="grid grid-cols-2 sm:grid-cols-4 gap-4">
    <div class="p-3 bg-blue-50 rounded-lg">
      <div class="text-xs text-blue-500 font-bold uppercase">Chain ID</div>
      <div id="chain-id-display" class="text-lg font-semibold text-main">-</div>
    </div>
    <div class="p-3 bg-green-50 rounded-lg">
      <div class="text-xs text-green-500 font-bold uppercase">Chain Name</div>
      <div id="chain-name-display" class="text-lg font-semibold text-main">-</div>
    </div>
    <div class="p-3 bg-yellow-50 rounded-lg">
      <div class="text-xs text-yellow-500 font-bold uppercase">Gas Price</div>
      <div id="chain-gas-display" class="text-lg font-semibold text-main">-</div>
    </div>
    <div class="p-3 bg-purple-50 rounded-lg">
      <div class="text-xs text-purple-500 font-bold uppercase">Native Coin</div>
      <div id="chain-coin-display" class="text-lg font-semibold text-main">-</div>
    </div>
  </div>
</div>
```
